sudo: false

os: osx

language: go

go:
  - 1.5.1

env:
  global:
    - GOPATH=/Users/travis/go
    - PATH=${GOPATH}/bin:$PATH
    - GO15VENDOREXPERIMENT=1
    - GOARCH=amd64
    - GOMAXPROCS=8
    - GOOS=darwin
    - HOMEBREW_MAKE_JOBS=9
before_install:
  - make update-deps
script:
  - make build-verbose
